# node_modules: This directory contains the installed dependencies of your project and is created when you run `npm install`.
node_modules

# dist: This directory contains the compiled version of your code and is generated by the `npm run build` command.
dist

# .git: This directory contains the Git version control information for your project and is not needed in the final Docker image.
.git

# README.md: This file provides information about your project and is not needed in the final Docker image.
README.md

# Dockerfile: This file is used to build the Docker image and is not needed in the final Docker image.
Dockerfile